name: Testing

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
jobs:
  setup-build:
    name: Ex1 (${{ matrix.python-version }}, ${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest"]
        python-version: [2.7]

    steps:
    - uses: actions/checkout@v2
    - name: Setup Conda
      uses: s-weigand/setup-conda@v1
      with:
        update-conda: false
        python-version: ${{ matrix.python-version }}

    - name: Install Env
      shell: bash
      run: |
        python --version
        conda create -q -n ph5 python=${{ matrix.python-version }}
        conda config --add channels conda-forge
        conda config --set restore_free_channel true
        conda env update --name ph5 --file environment.yml
        conda install flake8
    
    - name: Install Package and Run Test
      shell: bash
      run: |
        source activate ph5
        pip install -e . 
        bash create_ph5.sh
        python runtests.py

    - name: Check for Flake 8
      shell: bash
      run: |

        flake8 ph5
        pyflakes ph5
